### ISSUE TITLE
Suggestions on scraping play-by-play data

### ISSUE THREAD

**Issue by sri3705** [aj0strow/espn-scraper#9]
Hi,

I was interested in scraping the play by play data of a few NHL games. Do you have some recommendations on how to do it?

**Comment by dgmdan** [comment]
Currently, the gem doesn't offer any play by play data. It could theoretically be scraped but would be a serious undertaking - and one that differs a lot from sport to sport. I wouldn't be opposed to someone adding this feature (with tests) but I'm not sure that the demand is there. Personally, I don't need it.
